[package]
name = "rustls-connect-tests"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0 OR ISC OR MIT"
description = "Rustls connectivity based integration tests."
publish = false

[dependencies]
rustls = { path = "../rustls", package = "craftls", features = ["log"] }

[dev-dependencies]
regex = { workspace = true }
ring = { workspace = true }
rustls-aws-lc-rs = { path = "../rustls-aws-lc-rs" }
rustls-util = { path = "../rustls-util" }
tokio = { workspace = true }
webpki-roots = { workspace = true }

[lints]
workspace = true
